version: '3.3'

services:

 mihass-g-apache:
  build:
   context: ../
   dockerfile: Docker/ApacheDockerfile
  restart: always
  ports:
   - "80:80"    # turn to "81:80" when putting on gamecore
  volumes:
   - ../front_end:/usr/local/apache2/htdocs/
  networks:
   - net2


 mihass-g-server:
   build:
    context: ../
    dockerfile: Docker/ServerDockerfile
   restart: always
   ports:
    - "443:443" # turn to "8001:8080" when putting on gamecore
   volumes:
    - ../py:/app
   tty: true
   networks:
    - net2


 mihass-g-mysql:
  restart: always
  image: mysql:5.7.22
  ports:
    - "3306:3306"
  command: --innodb_use_native_aio=0
  environment:
   MYSQL_ROOT_PASSWORD: xboxorpc7
   MYSQL_DATABASE: ProjectOrganiser
  volumes:
    - ./MySQL:/docker-entrypoint-initdb.d
    - ./MySQL/data:/var/lib/mysql
  networks:
   - net2

networks:
  net2:
    driver: bridge
