version: '3.3'

services:

 apache:
  build:
   context: ../
   dockerfile: Docker/ApacheDockerfile
  ports:
   - "80:80"
  volumes:
   - ..:/usr/local/apache2/htdocs/MihassGProject

 server:
   build:
    context: ../
    dockerfile: Docker/ServerDockerfile
   ports:
    - "8080:8080"
   links:
    - mysql:mysql
   volumes:
    - ../py:/app
   tty: true


 mysql:
  image: mysql
  ports:
    - "3306:3306"
  environment:
   MYSQL_ROOT_PASSWORD: xboxorpc7
   MYSQL_DATABASE: MihassGProject
  volumes:
    - ./MySQL:/docker-entrypoint-initdb.d
    - ./MySQL/data:/var/lib/mysql
