version: '3.3'

services:

 mihass-g-apache:
  build:
   context: ../
   dockerfile: Docker/ApacheDockerfile
  ports:
   - "8002:80"    # turn to "81:80" when putting on gamecore
  networks:
   - "mihass-g-net"
  volumes:
   - ..:/usr/local/apache2/htdocs/

 mihass-g-server:
   build:
    context: ../
    dockerfile: Docker/ServerDockerfile
   ports:
    - "8001:8080" # turn to "8001:8080" when putting on gamecore
   networks:
    - "mihass-g-net"
   volumes:
    - ../py:/app
   tty: true


 mihass-g-mysql:
  image: mysql:5.7.22
  ports:
    - "8017:3306"
  command: --innodb_use_native_aio=0
  environment:
   MYSQL_ROOT_PASSWORD: xboxorpc7
   MYSQL_DATABASE: ProjectOrganiser
  networks:
   - "mihass-g-net"
  volumes:
    - ./MySQL:/docker-entrypoint-initdb.d
    - ./MySQL/data:/var/lib/mysql

networks:
  mihass-g-net:
    driver: bridge
